on:
  workflow:
    inputs:
      bugSigDBVersion:
        description: "BugSigDB Export Version"
        required: true
      bioconductorRelease:
        description: "Bioconductor Docker Release"
        required: true
        default: RELEASE_3_13

name: Dump BugSigDB

jobs:
  dump-bugsigdb:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:${{ github.event.inputs.bioconductorRelease }}

    steps:

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: BugSigDBExports

      - name: Checkout bugsigdbr 
        uses: actions/checkout@v2
        with:
          repository: waldronlab/bugsigdbr
          path: bugsigdbr

      - name: Export BugSigDB
        run: Rscript ${{ github.event.inputs.bugSigDBVersion }} ${{ GITHUB_WORKSPACE }}/BugSigDBExports

      - name: Commit Exports
        run: |
          git add ${{ GITHUB_WORKSPACE }}/BugSigDBExports/*
          git commit -m "Update files"
          git push origin main
