on:
  schedule:
    - cron: "0 22 * * 0" # UTC Time

name: Export BugSigDB

jobs:
  export-bugsigdb:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_13

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: BugSigDBExports

      - name: Checkout bugsigdbr 
        uses: actions/checkout@v2
        with:
          repository: waldronlab/bugsigdbr
          path: bugsigdbr

      - name: Setup git config
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports # Because we need to be a repository
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Install bugsigdbr 
        run: |
          cd $GITHUB_WORKSPACE/bugsigdbr
          Rscript -e "devtools::install()"

      - name: Export BugSigDB
        run: |
          echo $(date)
          Rscript $GITHUB_WORKSPACE/bugsigdbr/inst/scripts/dump_release.R $(date +'%F') $GITHUB_WORKSPACE/BugSigDBExports

      - name: Commit Exports
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports
          git add .
          git commit -m "Weekly export update"
          git push origin main
