on:
  workflow_dispatch:
    inputs:
      bugSigDBVersion:
        description: "BugSigDB Export Version"
        required: true
      bioconductorRelease:
        description: "Bioconductor Docker Release"
        required: true
        default: RELEASE_3_13

name: Export BugSigDB

jobs:
  export-bugsigdb:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:${{ github.event.inputs.bioconductorRelease }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: BugSigDBExports

      - name: Checkout bugsigdbr 
        uses: actions/checkout@v2
        with:
          repository: waldronlab/bugsigdbr
          path: bugsigdbr

      - name: Setup git config
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports # Because we need to be a repository
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Install bugsigdbr 
        run: |
          cd $GITHUB_WORKSPACE/bugsigdbr
          Rscript -e "devtools::install()"

      - name: Export BugSigDB
        run: Rscript $GITHUB_WORKSPACE/bugsigdbr/inst/scripts/dump_release.R ${{ github.event.inputs.bugSigDBVersion }} $GITHUB_WORKSPACE/BugSigDBExports

      - name: Commit Exports
        run: |
          git switch -c new-exports
          git add $GITHUB_WORKSPACE/BugSigDBExports/*
          git commit -m "Update files"
          git push origin new-exports
