on:
  workflow_dispatch:
    inputs:
      bugSigDBVersion:
        description: "BugSigDB Export Version"
        required: false
      bioconductorRelease:
        description: "Bioconductor Docker Release"
        required: true
        default: RELEASE_3_13

name: Export BugSigDB

jobs:
  export-bugsigdb:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:${{ github.event.inputs.bioconductorRelease }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: BugSigDBExports

      - name: Checkout bugsigdbr 
        uses: actions/checkout@v2
        with:
          repository: waldronlab/bugsigdbr
          path: bugsigdbr

      - name: Setup git config
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports # Because we need to be a repository
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Install bugsigdbr 
        run: |
          cd $GITHUB_WORKSPACE/bugsigdbr
          Rscript -e "devtools::install()"

      - name: Export BugSigDB
        run: |
          VERSION=${{ github.event.inputs.bugSigDBVersion }}
          if [[ -z "${VERSION}" ]]; then
              # Get version and increment patch number to determine the new version
              VERSION=$(head $GITHUB_WORKSPACE/BugSigDBExports/full_dump.tab | awk '/^[#]/ {print substr($3, 1, length($3)-1)}')
              PATCH=${VERSION##*.}
              NEW_PATCH=$((PATCH + 1))
              VERSION=${VERSION%.*}.$NEW_PATCH
          fi
          Rscript $GITHUB_WORKSPACE/bugsigdbr/inst/scripts/dump_release.R $VERSION $GITHUB_WORKSPACE/BugSigDBExports

      - name: Commit Exports
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports
          git switch -c new-exports
          git add .
          git commit -m "Update files"
          git push origin new-exports
